image: doowzs/golang-qcloud-ci:latest

variables:
  TZ: Asia/Shanghai
  # COS_USERID: defined in GitLab
  # COS_SECRET: defined in GitLab
  # COS_BUCKET: defined in GitLab
  # COS_REGION: defined in GitLab

before_script:
  - echo "Configuring timezone..."
  - ln -fs /usr/share/zoneinfo/$TZ /etc/localtime
  - echo "Current server time is '$(date)'."

  - echo "Extracting version string..."
  - export GOJ_VERSION=$(cat main.go | grep -Eo "Version string = \"([0-9.]+)\"" | cut -d'"' -f 2)
  - echo "GOJ version is $GOJ_VERSION"

  - echo "Moving source code to GOROOT..."
  - rm -rf $GOPATH/src/$CI_PROJECT_NAME
  - mkdir -p $GOPATH/src/$CI_PROJECT_NAME
  - cp -r $CI_PROJECT_DIR $GOPATH/src/

  - coscmd config
    -a $COS_USERID
    -s $COS_SECRET
    -b $COS_BUCKET
    -r $COS_REGION

source:
  script:
    - cd $GOPATH/src
    - tar czf goj-$GOJ_VERSION.orig.tar.gz -C $CI_PROJECT_NAME .
    - coscmd upload -s ./goj-$GOJ_VERSION.orig.tar.gz /goj/source/goj-$GOJ_VERSION.orig.tar.gz

debian:
  script:
    - cd $GOPATH/src/$CI_PROJECT_NAME
    - go get ./...
    - dpkg-source --before-build .
    - dpkg-buildpackage -us -uc -b
    - cd $GOPATH/src
    - coscmd upload -s ./goj-$GOJ_VERSION-0_amd64.deb /goj/debian/goj-$GOJ_VERSION-0_amd64.deb

windows:
  script:
    - cd $GOPATH/src
    - env GOOS=windows GOARCH=amd64 go build $CI_PROJECT_NAME
    - zip goj-$GOJ_VERSION_amd64.zip
    - coscmd upload -s ./goj-$GOJ_VERSION_amd64.zip /goj/windows/goj-$GOJ_VERSION_amd64.zip