image: doowzs/golang-qcloud-ci:latest

variables:
  TZ: Asia/Shanghai
  # COS_USERID: defined in GitLab
  # COS_SECRET: defined in GitLab
  # COS_BUCKET: defined in GitLab
  # COS_REGION: defined in GitLab

stages:
  - build
  - index

before_script:
  - echo "Configuring timezone..."
  - ln -fs /usr/share/zoneinfo/$TZ /etc/localtime
  - echo "Current server time is '$(date)'."

  - echo "Extracting version string..."
  - export VERSION=$(cat main.go | grep -Eo "Version string = \"([0-9.]+)\"" | cut -d'"' -f 2)
  - echo "GOJ version is $VERSION"

  - echo "Moving source code to GOROOT..."
  - rm -rf $GOPATH/src/$CI_PROJECT_NAME
  - mkdir -p $GOPATH/src/$CI_PROJECT_NAME
  - cp -r $CI_PROJECT_DIR $GOPATH/src/

  - coscmd config
    -a $COS_USERID
    -s $COS_SECRET
    -b $COS_BUCKET
    -r $COS_REGION

source:
  stage: build
  script:
    - cd $GOPATH/src
    - tar --transform='flags=r;s|goj|goj_$VERSION|' -czf goj_$VERSION.orig.tar.gz goj
    - coscmd upload ./goj_$VERSION.orig.tar.gz /goj/$VERSION/goj_$VERSION.orig.tar.gz
    - rm ./goj_$VERSION.orig.tar.gz

debian:
  stage: build
  script:
    - cd $GOPATH/src/$CI_PROJECT_NAME
    - go get ./...
    - dpkg-buildpackage -us -uc -b
    - cd $GOPATH/src
    - coscmd upload ./goj_$VERSION-0_amd64.deb /goj/$VERSION/goj_$VERSION-0_debian_amd64.deb
    - rm ./goj_$VERSION-0_amd64.*

linux:
  stage: build
  script:
    - cd $GOPATH/src/$CI_PROJECT_NAME
    - go get ./...
    - env GOOS=linux GOARCH=amd64 go build -o goj
    - zip ./goj_"$VERSION"_linux_amd64.zip goj README.md LICENSE
    - coscmd upload ./goj_"$VERSION"_linux_amd64.zip /goj/$VERSION/goj_"$VERSION"_linux_amd64.zip
    - rm ./goj ./goj_"$VERSION"_linux_amd64.zip

windows:
  stage: build
  script:
    - cd $GOPATH/src/$CI_PROJECT_NAME
    - go get ./...
    - env GOOS=windows GOARCH=amd64 go build -o goj.exe
    - zip ./goj_"$VERSION"_windows_amd64.zip goj.exe README.md LICENSE
    - coscmd upload ./goj_"$VERSION"_windows_amd64.zip /goj/$VERSION/goj_"$VERSION"_windows_amd64.zip
    - rm ./goj.exe ./goj_"$VERSION"_windows_amd64.zip