image: doowzs/golang-qcloud-ci:latest

variables:
  TZ: Asia/Shanghai
  # COS_USERID: defined in GitLab
  # COS_SECRET: defined in GitLab
  # COS_BUCKET: defined in GitLab
  # COS_REGION: defined in GitLab

stages:
  - build
  - publish

before_script:
  - echo "Configuring timezone..."
  - ln -fs /usr/share/zoneinfo/$TZ /etc/localtime
  - echo "Current server time is '$(date)'."

  - echo "Extracting version string..."
  - export GOJ_VERSION=$(cat main.go | grep -Eo "Version string = \"([0-9.]+)\"" | cut -d'"' -f 2)
  - echo "GOJ version is $GOJ_VERSION"

  - echo "Linking go library to GOROOT..."
  - mkdir -p /root/go
  - mkdir -p /root/go/src
  - ln -s $CI_PROJECT_DIR /root/go/src/$CI_PROJECT_NAME
  - go get

build:
  stage: build
  script:
    - go build

publish:
  stage: publish
  script:
    - coscmd config
      -a $COS_USERID
      -s $COS_SECRET
      -b $COS_BUCKET
      -r $COS_REGION
    - dpkg-source --before-build .
    - dpkg-buildpackage -us -uc -b
    - ls
